### ISSUE TITLE
can a fragment contain a layout that has fragments?

### ISSUE THREAD

**Issue by argyleink** [flackr/carousel#17]

**Comment by flackr** [comment]
I don't think so. What would this look like? I think the current direction is that the "fragment" is a selector for the virtual area of that fragment but that it does not in fact host a tree of content

**Comment by argyleink** [comment]
`virtual area of that fragment but that it does not in fact host a tree of content` i understand that as yes, layouts with fragments can have layouts with their own fragments, because they're virtual and wouldnt need to know or care about nesting or not.

**Comment by flackr** [comment]
Yes, you can have layouts that are fragmented within a fragmented layout, e.g. https://jsbin.com/xenibab/edit?html,output
In this case, yes, the second fragment would contain the fragmented layout.

I was taking your question to be whether the thing the fragment selects could be fragmented.
