### ISSUE TITLE
flowing example broken?

### ISSUE THREAD

**Issue by bkardell** [flackr/carousel#5]
This doesn't actually seem to work for me?

https://flackr.github.io/carousel/examples/fragmentation/flowing/

**Comment by flackr** [comment]
I assume you're using chrome or safari? It only fragments correctly in firefox for me:

<img width="904" alt="Screenshot 2024-02-07 at 6 49 53 PM" src="https://github.com/flackr/carousel/assets/366761/85103a16-61db-4513-af58-42109756a11b">

I'm going to file an issue for it, but chrome's column fragmentation seems to stop working when it needs to break inside a large element.

**Comment by flackr** [comment]
Filed https://g-issues.chromium.org/issues/324314465
